export const voices = [
  {
    name: "af_heart",
    quality: "A",
    overallGrade: "A",
    description: "Warm and emotive—ideal for heartfelt storytelling and empathetic brand messaging.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_alloy",
    quality: "B",
    overallGrade: "C",
    description: "Solid and dependable timbre, perfect for technical explainers with a friendly twist.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_aoede",
    quality: "B",
    overallGrade: "C+",
    description: "Smooth and melodic tones that elevate lifestyle content and podcast intros.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_bella",
    quality: "A",
    overallGrade: "A-",
    description: "Vibrant and energetic delivery—engineered for high-impact promotional spots.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_jessica",
    quality: "C",
    overallGrade: "D",
    description: "Conversational and down-to-earth, well-suited for internal training clips.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_kore",
    quality: "B",
    overallGrade: "C+",
    description: "Clear mid-range presence, optimised for product how-to videos.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_nicole",
    quality: "B",
    overallGrade: "B-",
    description: "Relaxed yet precise articulation, great for customer-service IVR flows.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_nova",
    quality: "B",
    overallGrade: "C",
    description: "Forward-leaning, youthful vibe that resonates with modern audiences.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_river",
    quality: "C",
    overallGrade: "D",
    description: "Laid-back and informal cadence, perfect for casual social content.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_sarah",
    quality: "B",
    overallGrade: "C+",
    description: "Measured and articulate—ideal for compliance or policy narration.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "af_sky",
    quality: "B",
    overallGrade: "C-",
    description: "Airy and optimistic tone that lifts lifestyle vignettes.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "am_adam",
    quality: "D",
    overallGrade: "F+",
    description: "Rugged and authentic—useful for niche, character-driven reads.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_echo",
    quality: "C",
    overallGrade: "D",
    description: "Neutral and consistent voice, suitable for general narration at scale.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_eric",
    quality: "C",
    overallGrade: "D",
    description: "Steady baritone providing reliability for budget-conscious projects.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_fenrir",
    quality: "B",
    overallGrade: "C+",
    description: "Confident and bold resonance—ideal for gaming trailers and ads.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_liam",
    quality: "C",
    overallGrade: "D",
    description: "Approachable and easy-going nature tailored for community outreach.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_onyx",
    quality: "C",
    overallGrade: "D",
    description: "Deep and steady tone that brings gravitas to documentary pieces.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_puck",
    quality: "B",
    overallGrade: "C+",
    description: "Playful pace with crisp diction—great for explainer animations.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "am_santa",
    quality: "C",
    overallGrade: "D-",
    description: "Warm, jovial resonance that shines in festive campaigns.",
    gender: "male",
    language: "English-America",
  },
  {
    name: "bf_alice",
    quality: "C",
    overallGrade: "D",
    description: "Soft and reassuring RP accent—perfect for wellness content.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "bf_emma",
    quality: "B",
    overallGrade: "B-",
    description: "Elegant and engaging delivery that uplifts premium brand stories.",
    gender: "female",
    language: "English-America",
  },
  {
    name: "bf_isabella",
    quality: "B",
    overallGrade: "C",
    description: "Bright and friendly articulation suited for e-commerce walkthroughs.",
    gender: "female",
    language: "English-British",
  },
  {
    name: "bf_lily",
    quality: "C",
    overallGrade: "D",
    description: "Gentle cadence fostering trust in educational modules.",
    gender: "female",
    language: "English-British",
  },
  {
    name: "bm_daniel",
    quality: "C",
    overallGrade: "D",
    description: "Straightforward and pragmatic—ideal for factual news bulletins.",
    gender: "male",
    language: "English-British",
  },
  {
    name: "bm_fable",
    quality: "B",
    overallGrade: "C",
    description: "Story-centric intonation that brings narratives to life.",
    gender: "male",
    language: "English-British",
  },
  {
    name: "bm_george",
    quality: "B",
    overallGrade: "C",
    description: "Crisp RP delivery lending authority to corporate presentations.",
    gender: "male",
    language: "English-British",
  },
  {
    name: "bm_lewis",
    quality: "C",
    overallGrade: "D+",
    description: "Cool and collected tone, excellent for support chat-bot personas.",
    gender: "male",
    language: "English-British",
  },
];
