export const voices = [
  {
    name: 'af_heart',
    title: 'Sienna',
    quality: 'A',
    overallGrade: 'A',
    description: 'Warm and emotive—ideal for heartfelt storytelling and empathetic brand messaging.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_alloy',
    title: 'Talia',
    quality: 'B',
    overallGrade: 'C',
    description: 'Solid and dependable timbre, perfect for technical explainers with a friendly twist.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_aoede',
    title: 'Aubrey',
    quality: 'B',
    overallGrade: 'C+',
    description: 'Smooth and melodic tones that elevate lifestyle content and podcast intros.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_bella',
    title: 'Bella',
    quality: 'A',
    overallGrade: 'A-',
    description: 'Vibrant and energetic delivery—engineered for high-impact promotional spots.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_jessica',
    title: 'Jessica',
    quality: 'C',
    overallGrade: 'D',
    description: 'Conversational and down-to-earth, well-suited for internal training clips.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_kore',
    title: 'Kora',
    quality: 'B',
    overallGrade: 'C+',
    description: 'Clear mid-range presence, optimised for product how-to videos.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_nicole',
    title: 'Nicole',
    quality: 'B',
    overallGrade: 'B-',
    description: 'Relaxed yet precise articulation, great for customer-service IVR flows.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_nova',
    title: 'Nova',
    quality: 'B',
    overallGrade: 'C',
    description: 'Forward-leaning, youthful vibe that resonates with modern audiences.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_river',
    title: 'River',
    quality: 'C',
    overallGrade: 'D',
    description: 'Laid-back and informal cadence, perfect for casual social content.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_sarah',
    title: 'Sarah',
    quality: 'B',
    overallGrade: 'C+',
    description: 'Measured and articulate—ideal for compliance or policy narration.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'af_sky',
    title: 'Skylar',
    quality: 'B',
    overallGrade: 'C-',
    description: 'Airy and optimistic tone that lifts lifestyle vignettes.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'am_adam',
    title: 'Adam',
    quality: 'D',
    overallGrade: 'F+',
    description: 'Rugged and authentic—useful for niche, character-driven reads.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_echo',
    title: 'Eli',
    quality: 'C',
    overallGrade: 'D',
    description: 'Neutral and consistent voice, suitable for general narration at scale.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_eric',
    title: 'Eric',
    quality: 'C',
    overallGrade: 'D',
    description: 'Steady baritone providing reliability for budget-conscious projects.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_fenrir',
    title: 'Felix',
    quality: 'B',
    overallGrade: 'C+',
    description: 'Confident and bold resonance—ideal for gaming trailers and ads.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_liam',
    title: 'Liam',
    quality: 'C',
    overallGrade: 'D',
    description: 'Approachable and easy-going nature tailored for community outreach.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_onyx',
    title: 'Onyx',
    quality: 'C',
    overallGrade: 'D',
    description: 'Deep and steady tone that brings gravitas to documentary pieces.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_puck',
    title: 'Puck',
    quality: 'B',
    overallGrade: 'C+',
    description: 'Playful pace with crisp diction—great for explainer animations.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'am_santa',
    title: 'Nicholas',
    quality: 'C',
    overallGrade: 'D-',
    description: 'Warm, jovial resonance that shines in festive campaigns.',
    gender: 'male',
    language: 'English-America',
  },
  {
    name: 'bf_alice',
    title: 'Alice',
    quality: 'C',
    overallGrade: 'D',
    description: 'Soft and reassuring RP accent—perfect for wellness content.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'bf_emma',
    title: 'Emma',
    quality: 'B',
    overallGrade: 'B-',
    description: 'Elegant and engaging delivery that uplifts premium brand stories.',
    gender: 'female',
    language: 'English-America',
  },
  {
    name: 'bf_isabella',
    title: 'Isabella',
    quality: 'B',
    overallGrade: 'C',
    description: 'Bright and friendly articulation suited for e-commerce walkthroughs.',
    gender: 'female',
    language: 'English-British',
  },
  {
    name: 'bf_lily',
    title: 'Lily',
    quality: 'C',
    overallGrade: 'D',
    description: 'Gentle cadence fostering trust in educational modules.',
    gender: 'female',
    language: 'English-British',
  },
  {
    name: 'bm_daniel',
    title: 'Daniel',
    quality: 'C',
    overallGrade: 'D',
    description: 'Straightforward and pragmatic—ideal for factual news bulletins.',
    gender: 'male',
    language: 'English-British',
  },
  {
    name: 'bm_fable',
    title: 'Fable',
    quality: 'B',
    overallGrade: 'C',
    description: 'Story-centric intonation that brings narratives to life.',
    gender: 'male',
    language: 'English-British',
  },
  {
    name: 'bm_george',
    title: 'George',
    quality: 'B',
    overallGrade: 'C',
    description: 'Crisp RP delivery lending authority to corporate presentations.',
    gender: 'male',
    language: 'English-British',
  },
  {
    name: 'bm_lewis',
    title: 'Lewis',
    quality: 'C',
    overallGrade: 'D+',
    description: 'Cool and collected tone, excellent for support chat-bot personas.',
    gender: 'male',
    language: 'English-British',
  },
]
